
blank_issues_enabled: true
contact_links:
  - name: Bug Report
    url: https://github.com/jSagvold28/Programmer-Netlink/blob/main/.github/ISSUE_TEMPLATE/bug.md
    about: Create a bug report
  - name: Feature Request
    url: https://github.com/jSagvold28/ProgrammerIN/tree/main/.github/ISSUE_TEMPLATE
    about: Create a feature that you would like to see in ProgrammerIN
